[build]
  command = "echo 'No build command needed for static site'"
  publish = "."

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[context.production.environment]
  ENVIRONMENT = "production"

[dev]
  framework = "static"
  port = 8080